import { CompanyInfo, ServiceItem, SpecialOffer, BlockMaterial } from './types';

export const COMPANY_INFO: CompanyInfo = {
  name: 'FlowBlocos',
  tagline: 'Fábrica & Distribuidora de Materiais de Blocos de Concreto',
  phone: '(11) 4003-8290',
  phoneRaw: '+551140038290',
  email: 'vendas@flowblocos.com.br',
  hours: 'Seg - Sex: 07:00 às 17:30 | Sáb: 07:30 às 12:00',
  address: 'Distrito Industrial - Entregas para Toda a Região Metropolitana e Interior',
  deliveryCoverage: 'Entrega rápida com caminhão munk paletizado no canteiro de obras',
  emergencyService: 'Plantão de Cotações & Pedidos Rápidos',
  experienceYears: 12,
  completedProjects: 5200,
};

export const SERVICES_LIST: ServiceItem[] = [
  {
    id: 'modulacao-quantitativo',
    title: 'Cálculo de Modulação & Quantitativo',
    description: 'Análise de planta para paginação exata de blocos, meio blocos e canaletas, garantindo desperdício zero na sua obra.',
    iconName: 'structural',
    startingPrice: 'Grátis no pedido',
  },
  {
    id: 'entrega-paletizada',
    title: 'Entrega Paletizada com Caminhão Munk',
    description: 'Descarga mecanizada no canteiro de obras com precisão, rapidez e sem quebras de peças.',
    iconName: 'delivery',
    startingPrice: 'Frete sob medida',
  },
  {
    id: 'venda-direta-atacado',
    title: 'Venda Direta de Fábrica (Atacado & Varejo)',
    description: 'Tabelas diferenciadas para construtoras, condomínios, depósitos e reformas particulares.',
    iconName: 'wholesale',
    startingPrice: 'Preço de fábrica',
  },
  {
    id: 'laudos-certificados',
    title: 'Ensaios Técnicos & Certificados ABNT',
    description: 'Laudos de compressão e absorção emitidos por lote conforme as normas ABNT NBR 6136 e NBR 12118.',
    iconName: 'testing',
    startingPrice: 'Certificado incluso',
  },
];

export const SPECIAL_OFFERS: SpecialOffer[] = [
  {
    id: 'offer-eps',
    title: 'Bloco de Concreto com EPS (100x50x15cm) - Lote 100 un',
    price: 'R$ 8.900,00',
    originalPrice: 'R$ 9.800,00',
    note: '*100 blocos = ~50 m² de parede pronta já com reboco',
    code: 'BLOCOSFORTE100',
    iconName: 'structural',
  },
  {
    id: 'offer-estrutural',
    title: 'Palete Bloco Estrutural 14x19x39',
    price: 'R$ 4,35 / un',
    originalPrice: 'R$ 5,20 / un',
    note: '*Condição especial para carga fechada',
    code: 'ESTRUTURAL10',
    iconName: 'structural',
  },
  {
    id: 'offer-paver',
    title: 'Piso Intertravado Paver 6cm',
    price: 'R$ 44,90 / m²',
    originalPrice: 'R$ 54,00 / m²',
    note: '*Pronta entrega no atacado',
    code: 'PAVER44',
    iconName: 'delivery',
  },
  {
    id: 'offer-vedacao',
    title: 'Bloco de Vedação 14x19x39',
    price: 'R$ 3,45 / un',
    originalPrice: 'R$ 4,10 / un',
    note: '*Preço direto da usina',
    code: 'VEDACAO345',
    iconName: 'wholesale',
  },
];

export const BLOCO_FORTE_EPS_DETAILS = {
  brand: 'BLOCO FORTE',
  tagline: 'TECNOLOGIA QUE CONSTRÓI CONFORTO E SEGURANÇA',
  slogan: 'O bloco que faz a diferença na sua obra!',
  productTitle: 'BLOCO DE CONCRETO COM EPS',
  productSubtitle: 'Mais conforto, praticidade e economia para sua obra!',
  badge: 'Leve, resistente e de alta qualidade!',
  dimensions: '100 x 50 x 15 cm',
  dimensionsLabel: 'Tamanho: 100 x 50 x 15 cm',
  benefits: [
    {
      id: 'leve',
      title: 'LEVE',
      description: 'Facilita o transporte e a execução.',
      icon: 'feather',
    },
    {
      id: 'termico',
      title: 'CONFORTO TÉRMICO',
      description: 'Mantém o ambiente mais agradável.',
      icon: 'thermometer',
    },
    {
      id: 'acustico',
      title: 'CONFORTO ACÚSTICO',
      description: 'Reduz ruídos.',
      icon: 'volume',
    },
    {
      id: 'resistente',
      title: 'RESISTENTE',
      description: 'Mais segurança para sua obra.',
      icon: 'shield',
    },
  ],
  pricingTable: [
    { quantity: '1 unidade', value: 'R$ 89,00' },
    { quantity: '100 unidades', value: 'R$ 8.900,00' },
  ],
  rendimento: {
    title: 'RENDIMENTO',
    highlight: '100 BLOCOS = APROXIMADAMENTE 50 m²',
    subtext: 'DE PAREDE PRONTA, JÁ COM REBOCO.',
  },
  conditions: {
    delivery: 'Entrega: consultar valor.',
    payment: 'Pagamento: consultar condições.',
    guarantee: 'Qualidade e segurança em cada detalhe.',
    footerSlogan: 'Invista em qualidade!',
  },
};

export const PLUMBING_MATERIALS: BlockMaterial[] = [
  {
    id: 'bloco-concreto-eps',
    name: 'Bloco de Concreto com EPS (100x50x15cm) - Bloco Forte',
    category: 'Termoacústico Modular',
    dimensions: '100 x 50 x 15 cm',
    resistance: 'Alta Resistência • 50m² a cada 100 un',
    description: 'Mais conforto, praticidade e economia. Bloco leve com miolo de EPS (isopor) que garante isolamento térmico e acústico, já pronto com acabamento.',
    price: 'R$ 89,00',
    originalPrice: 'R$ 98,00',
    badge: 'LANÇAMENTO BLOCO FORTE',
    rating: 5.0,
    reviewsCount: 312,
    imageUrl: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=600&q=80',
    altText: 'Bloco de concreto com miolo de EPS 100x50x15cm Bloco Forte com fundo transparente',
    stockStatus: 'Pronta Entrega',
  },
  {
    id: 'bloco-estrutural-14',
    name: 'Bloco de Concreto Estrutural 14x19x39',
    category: 'Alvenaria Estrutural',
    dimensions: '14 x 19 x 39 cm',
    resistance: 'fck ≥ 8.0 MPa',
    description: 'Bloco vazado autoportante de alta resistência mecânica, arestas vivas e precisão milimétrica para edifícios e muros de contenção.',
    price: 'R$ 4,35',
    originalPrice: 'R$ 5,20',
    badge: 'MAIS VENDIDO',
    rating: 4.9,
    reviewsCount: 248,
    imageUrl: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?auto=format&fit=crop&w=600&q=80',
    altText: 'Bloco de Concreto Estrutural 14x19x39cm em palete na obra',
    stockStatus: 'Pronta Entrega',
  },
  {
    id: 'bloco-vedacao-14',
    name: 'Bloco de Concreto para Vedação 14x19x39',
    category: 'Vedação & Fechamento',
    dimensions: '14 x 19 x 39 cm',
    resistance: 'fck ≥ 3.0 MPa',
    description: 'Indicado para fechamento de vãos em estruturas de concreto armado, garantindo isolamento termoacústico e menor peso próprio.',
    price: 'R$ 3,45',
    originalPrice: 'R$ 4,10',
    badge: 'ECONÔMICO',
    rating: 4.8,
    reviewsCount: 180,
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb186156a?auto=format&fit=crop&w=600&q=80',
    altText: 'Parede levantada com blocos de concreto de vedação com juntas alinhadas',
    stockStatus: 'Em estoque',
  },
  {
    id: 'canaleta-concreto-u',
    name: 'Canaleta de Concreto "U" 14x19x39',
    category: 'Canaletas & Vigas',
    dimensions: '14 x 19 x 39 cm',
    resistance: 'fck ≥ 4.5 MPa',
    description: 'Canaleta com seção em "U" para moldagem rápida de vergas, contravergas e cintas de amarração sem necessidade de formas de madeira.',
    price: 'R$ 5,80',
    originalPrice: 'R$ 6,90',
    badge: 'PRÁTICO',
    rating: 4.9,
    reviewsCount: 115,
    imageUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=600&q=80',
    altText: 'Canaleta de concreto tipo U para viga de amarração',
    stockStatus: 'Em estoque',
  },
  {
    id: 'paver-intertravado-6cm',
    name: 'Piso Intertravado Paver Holandês 10x20x6',
    category: 'Pisos & Pavimentação',
    dimensions: '10 x 20 x 6 cm',
    resistance: 'fck ≥ 35 MPa',
    description: 'Pavimento intertravado de concreto de alta compactação para garagens, calçadas, pátios industriais e condomínios.',
    price: 'R$ 44,90 / m²',
    originalPrice: 'R$ 54,00 / m²',
    badge: 'ALTA RESISTÊNCIA',
    rating: 4.9,
    reviewsCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?auto=format&fit=crop&w=600&q=80',
    altText: 'Pavimentação de calçada com pisos intertravados pavers de concreto',
    stockStatus: 'Pronta Entrega',
  },
  {
    id: 'cobogo-decorativo-concreto',
    name: 'Cobogó Decorativo de Concreto 39x39x7',
    category: 'Elementos Vazados',
    dimensions: '39 x 39 x 7 cm',
    resistance: 'Acabamento Liso',
    description: 'Bloco vazado arquitetônico para fachadas e divisórias que privilegiam luz natural, ventilação cruzada e estética moderna.',
    price: 'R$ 29,90',
    originalPrice: 'R$ 38,00',
    badge: 'DECORATIVO',
    rating: 5.0,
    reviewsCount: 92,
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=600&q=80',
    altText: 'Fachada moderna com cobogós de concreto vazados',
    stockStatus: 'Em estoque',
  },
  {
    id: 'meio-bloco-estrutural',
    name: 'Meio Bloco de Concreto Estrutural 14x19x19',
    category: 'Compensadores & Modulação',
    dimensions: '14 x 19 x 19 cm',
    resistance: 'fck ≥ 8.0 MPa',
    description: 'Peça essencial para modulação e amarração de cantos e vãos de portas/janelas sem necessidade de corte no canteiro de obras.',
    price: 'R$ 2,75',
    originalPrice: 'R$ 3,30',
    badge: 'ZERO QUEBRA',
    rating: 4.8,
    reviewsCount: 85,
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=600&q=80',
    altText: 'Meio bloco de concreto para amarração de alvenaria',
    stockStatus: 'Em estoque',
  },
  {
    id: 'bloco-celular-cca',
    name: 'Bloco de Concreto Celular Autoclavado (CCA)',
    category: 'Blocos Leves & Térmicos',
    dimensions: '15 x 30 x 60 cm',
    resistance: 'Isolamento Térmico/Acústico',
    description: 'Bloco ultra leve com alta velocidade de assentamento, corte fácil com serrote e excelente desempenho contra chamas e ruídos.',
    price: 'R$ 19,50',
    originalPrice: 'R$ 24,00',
    badge: 'TÉRMICO & LEVE',
    rating: 4.9,
    reviewsCount: 64,
    imageUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=600&q=80',
    altText: 'Bloco de concreto celular autoclavado leve',
    stockStatus: 'Em estoque',
  },
  {
    id: 'grout-alvenaria-25kg',
    name: 'Grout Industrializado para Alvenaria 25kg',
    category: 'Argamassas & Preenchimento',
    dimensions: 'Saco 25 kg',
    resistance: 'fck ≥ 25 MPa',
    description: 'Microconcreto fluido de alta resistência e retração compensada para preenchimento de alvéolos e cintas em alvenaria estrutural.',
    price: 'R$ 32,90',
    originalPrice: 'R$ 39,00',
    badge: 'ALTA FLUIDEZ',
    rating: 4.8,
    reviewsCount: 118,
    imageUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
    altText: 'Saco de grout industrializado para alvenaria de blocos',
    stockStatus: 'Em estoque',
  },
];

export const WELCOME_POINTS = [
  { title: 'Blocos Certificados ABNT NBR 6136', desc: 'Controle de qualidade e laudos de resistência mecânica por lote' },
  { title: 'Preço Direto de Fábrica', desc: 'Melhor custo por m² com economia comprovada para sua obra' },
  { title: 'Entrega Paletizada com Caminhão Munk', desc: 'Descarga mecanizada ágil e segura direto no seu canteiro de obras' },
  { title: 'Geometria Precisa & Zero Quebra', desc: 'Arestas vivas e dimensões uniformes que reduzem o consumo de argamassa' },
  { title: 'Cálculo Gratuito de Modulação', desc: 'Engenharia técnica para calcular a quantidade exata de peças' },
  { title: 'Mais de 5.200 Obras Atendidas', desc: 'Fornecimento confiável para construtoras, loteamentos e reformas' },
];

export const NAV_LINKS = [
  { name: 'Início', href: '#home', current: true },
  { name: 'A Fábrica', href: '#about' },
  { name: 'Soluções & Serviços', href: '#services', hasDropdown: true },
  { name: 'Catálogo de Blocos', href: '#materiais' },
  { name: 'Solicitar Cotação', href: '#contact' },
];
